### ISSUE TITLE
ETH preprocessing

### ISSUE THREAD

**Issue by jwohland** [jwohland/lucas_3dwinds#14]
Edouard made his data available. It is provided in annually zipped folders (e.g., one for 1979, another one for 1980 etc) and contains 3D winds at 850hPa and 925hPa (`output/3D`) as well as 10m winds (`output/6hr`) with one file per timestep.

**Comment by jwohland** [comment]
Mail from Edouard: Surface roughness is in streams h0 to h3 where land surface model outputs are stored.

**Comment by jwohland** [comment]
It appears that more vertical levels were available for Meier et al. analysis, so decided to double check with Edouard whether I haven't missed anything

**Comment by jwohland** [comment]
There is a `2015_old.tar` and a `2015.tar` folder. 

@edavin I assume that I can delete the old folder, correct?

**Comment by jwohland** [comment]
Overview of relevant variables, their names, and where they are stored

| variable name      | long_name | in which file     |
| :---        |    :----:   |          ---: |
| `FI`      | geopotential       |  `3D`  |
| `QV`      | specific humidity       |  `3D`  |
| `T`      | temperature       |  `3D`  |
| `U`      |  U-component of wind      |  `3D`  |
| `V`      |  V-component of wind      |  `3D`  |
| `RELHUM`      |  relative humidity      |  `3D`  |
| `U_10M`      |  U-component of 10m wind      |  `6hr`  |
| `V_10M`      |  U-component of 10m wind      |  `6hr`  |
| `landmask`      | land/ocean mask (0.=ocean and 1.=land)       |  `h0`  |
| `landfrac`   | Land fraction       | `h0`      |


See ff1774ccce9a36be81d8d0c0c5067ec892a04ddb for an overview of all variables. There isn't a single variable containing the word "roughness", so I assume that roughness data is not directly available. 

- [x] Double check this with Edouard

**Comment by jwohland** [comment]
e9b0face93004936b54f098db1ae111a48842f66 

Preprocessing implemented to extent that script needs to be executed. Will wait until January because this probably shouldn't be done on a interactive node (expect, 3mins/year/experiment --> 3x30x3 mins =  270mins = 4,5h)

**Comment by edavin** [comment]
> 
yes old folders can be deleted

**Comment by jwohland** [comment]
There is an issue with `u_10` and `v_10` which currently isn't found.
- [x] Fixed (b05acaa)

**Example**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/20681098/211334943-3adb4e27-8535-4128-96ea-b3240c0ac37a.png">

**Comment by jwohland** [comment]
I succesfully ran `preprocess_ETH.sh` and all outputs seem fine
