### ISSUE TITLE
GERICS preprocessing

### ISSUE THREAD

**Issue by jwohland** [jwohland/lucas_3dwinds#9]
GERICS data from the archive is structured differently than the desired 

> institution/experiment/variable/*.nc

structure:

1.  The experiments use numbers that stand for EVAL, FOREST, GRASS
2. multiple variables are stored in the same .nc file

And the content has some surprises:

1.  some variables have an offset of half a grid box: wind components are shifted horizontally and geopotential is shifted vertically
2. calender entries are floats. Example: First timestep is at `19790101.25` corresponding to 1st January 1979 at 6AM

- [x] check if time is UTC
- [x] In exploratory analysis, I simply replaced coordinates to bring on fields on the same grid (see snippets below): does that make sense? 

```
# bring wind variables on same grid. Their grids are shifted by half a cell east or northward
ds["U"] = (
    ds["U"].assign_coords({"rlon_2": ds.rlon.values}).rename({"rlon_2": "rlon"})
)
ds["V"] = (
    ds["V"].assign_coords({"rlat_2": ds.rlat.values}).rename({"rlat_2": "rlat"})
)

# bring geopotential on same grid
ds["FI"] = ds["FI"].rename(
    {"lev_2": "lev"}
)  # todo check that this actually makes sense
```

**Comment by jwohland** [comment]
**Internal discussion results:**
Wind speeds in center of grid box can be calculated from wind speeds at the grid box edges as

> s^2= [ (u_left + u_right) / 2 ]^2 + [ (v_top + v_bottom) / 2 ] ^2 

where left, right, top, down are directions when looking at the grid cell from above. That is, left is western edge of the cell, top is northern edge etc.

We don't really understand why there are two different vertical levels `lev` and `lev2`. 

- [x] Ask Joni and/or Kevin.

**Comment by jwohland** [comment]
Wind speeds are reported on numbered levels `lev` but we do not know the geopotential at those heights. Geopotential is instead reported on shifted `lev_2` levels. 

Kevin recommends to use the mean between two geopotentials to compute the geopotential at `lev`.

This sounds very error prone, in particular because `lev` and `lev_2` have the same number of entries and values at the top have to be added to ensure that the mean is always defined.  
- [x] Develop a jupyter notebook and share with Kevin to double check approach

**Comment by jwohland** [comment]
@peterhoffmanngerics Could you have a look at this notebook where I implemented a quick and dirty version of how to bring GERICS winds and geopential and everything else on the same grid? Does that approach seem sensible to you?

[notebooks/3_GERICS_grid_offsets.ipynb](https://github.com/jwohland/lucas_3dwinds/blob/8d5d1f41e18928cba0cd08af481cd8dba5dc5fed/notebooks/3_GERICS_grid_offsets.ipynb)

**Comment by peterhoffmanngerics** [comment]
I've checked the code and it looks fine to me. For future REMO output, we should consider n+2 grid points for Wind output to cover the whole Arakawa C grid, which is use by REMO. In addition, the issue with the two different vertical levels for geopotential and wind components still remains.

**Comment by jwohland** [comment]
Need to decide whether to keep `FI`, `FIB` and `FI_interpolated` folders. Tendency is to delete `FI` and rename the last to `FI`

- [ ] Decide and implement

**Comment by jwohland** [comment]
Added wind speed `s` computation and tested for one year and experiment. Needs to be executed. And then

- [ ] make a decision whether or not to keep `U` and `V`

**Comment by jwohland** [comment]
GERICS calender not understood by xarray... Can not be parse and monthly regrouping does not work out of the box

**Comment by jwohland** [comment]
Calender solution implemented by manual definition
